// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl53AUb3FrIxiB-uWI8u9cLjGIWPofA5k',
    appId: '1:486151944621:web:b2f0d39c7736b084dc8924',
    messagingSenderId: '486151944621',
    projectId: 'mydiet-apps',
    authDomain: 'mydiet-apps.firebaseapp.com',
    storageBucket: 'mydiet-apps.firebasestorage.app',
    measurementId: 'G-90PXEH7DKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc7EsikoRe54ebU1MQPPcJTx_03ygS9Ac',
    appId: '1:486151944621:android:6bb020e173a958cfdc8924',
    messagingSenderId: '486151944621',
    projectId: 'mydiet-apps',
    storageBucket: 'mydiet-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBROdQroJAvri6cnFKIiJX0qJXqDGh8ZdY',
    appId: '1:486151944621:ios:a4353c03e391d399dc8924',
    messagingSenderId: '486151944621',
    projectId: 'mydiet-apps',
    storageBucket: 'mydiet-apps.firebasestorage.app',
    iosBundleId: 'com.example.fitmindAi',
  );
}
